Update main branch with all tasks performed in the preview branch
manuel-salvador/maxwood-ecommerce pull request #1
Opened 2023-07-27 15:47 UTC by manuel-salvador

This PR is to update the main branch with all the tasks that were already performed and approved during the previous sprint.

2023-07-27 20:16 UTC, brayanlaiton0116 approved these changes
No se encuentra ningún fallo se aprueba la tarea

2023-07-27 20:19 UTC, brayanlaiton0116 requested changes
Se revisa la tarea al detalla y se sugiere no utilizar abreviaturas o contracciones

2023-07-27 20:19 UTC, brayanlaiton0116 commented on src/pages/sobre-nosotros/index.tsx
> +            <h3 className="text-2xl sm:text-xl font-semibold my-4">
No utilizar abreviaturas o contracciones no queda muy clara la clase.

2023-07-28 14:52 UTC, manuel-salvador commented on src/pages/sobre-nosotros/index.tsx
> +            <h3 className="text-2xl sm:text-xl font-semibold my-4">
Estoy usando Tailwind el cual es utility-first es decir, no es css normal sino que funciona como por ejemplo bootstrap.
Dejo la pagina de tailwind a continuacion:
[Taiwind CSS](https://tailwindcss.com/)

2023-07-28 17:09 UTC, saracast909 approved these changes

2023-07-31 18:57 UTC, brayanlaiton0116 commented on src/pages/sobre-nosotros/index.tsx
> +            <h3 className="text-2xl sm:text-xl font-semibold my-4">
okey, instalaste de  tailwindcss ya me quedo mas claro

2023-07-31 18:59 UTC, brayanlaiton0116 approved these changes
aprobado

2023-08-01 13:13 UTC, merged